### PR TITLE
add testing saved model functionality in train.py

### PR DESCRIPTION
**Pull request by zhouzypaul**
using `python3 -m actgen.train --test` to test saved model

### CODE REVIEW

**Comment by zhouzypaul** [comment]
@camall3n the tests have failed because the `results` folder is ignored. Should we un-ignore those, or not add the testing functionality in `train.py`?

**Comment by camall3n** [comment]
My preference is not to clutter the training script with the code for the second experiment. I'm willing to tolerate a little bit of code duplication in order to improve readability and to keep these things from ever interfering with each other.

**Comment by zhouzypaul** [comment]
gotcha. I have that separate testing script stashed locally. Do we want that to be in the repo? @camall3n

**Comment by camall3n** [comment]
Yeah let's add it. Maybe as a separate PR.

I'm confused though. The latest PR passed all the checks. What's breaking on your end?

**Comment by zhouzypaul** [comment]
it's not passing because I made the `--test` option in `train.py` load in the saved models, but the saved model files are ignored in git history. 

Cool. I'll close this and do another PR.

**Comment by camall3n** [comment]
Oh I see, my intent with `--test` mode was just to give us a way of quickly making sure the program runs and that everything is hooked up properly

**Pull request closed without merging**
